name: Deploy Endatix

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: The name of the environment to deploy to
        required: true
      api_slot_name:
        type: string
        description: The name of the slot to deploy to
        required: false
        default: "Production"

jobs:
  deploy-api:
    name: "Endatix API"
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
    outputs:
      api-url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: endatix-api

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_APP_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_APP_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.API_WEB_APP_NAME }}
          slot-name: ${{ inputs.api_slot_name }}
          package: .
    
  deploy-hub:
    name: "Endatix Hub"
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy-to-static-web-app.outputs.static_web_app_url }}
    outputs:
      hub-url: ${{ steps.deploy-to-static-web-app.outputs.static_web_app_url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: endatix-hub

      - name: 📚 Set env file prior to build
        run: |
          cd .next/standalone
          ENV_FILE=".env"
          if [ "${{ inputs.environment }}" = "Production" ]; then
            ENV_FILE=".env.production"
          fi
          touch $ENV_FILE
          echo ENDATIX_BASE_URL=${{ secrets.ENDATIX_BASE_URL }} >> $ENV_FILE
          echo SESSION_SECRET=${{ secrets.ENDATIXHUB_SESSION_SECRET }} >> $ENV_FILE
          echo NEXT_FORMS_COOKIE_NAME=${{ secrets.ENDATIXHUB_NEXT_FORMS_COOKIE_NAME }} >> $ENV_FILE
          echo NEXT_FORMS_COOKIE_DURATION_DAYS=${{ secrets.ENDATIXHUB_SESSION_SECRET }} >> $ENV_FILE
          echo SLACK_CLIENT_ID=${{ secrets.ENDATIXHUB_SLACK_CLIENT_ID }} >> $ENV_FILE
          echo SLACK_CLIENT_SECRET=${{ secrets.ENDATIXHUB_SLACK_CLIENT_SECRET }} >> $ENV_FILE
          echo SLACK_REDIRECT_URI=${{ secrets.ENDATIXHUB_SLACK_REDIRECT_URI }} >> $ENV_FILE
          echo NEXT_PUBLIC_MAX_IMAGE_SIZE=${{ vars.NEXT_PUBLIC_MAX_IMAGE_SIZE }} >> $ENV_FILE

      - name: Deploy
        id: deploy-to-static-web-app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.HUB_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ""
          output_location: ""
          skip_app_build: true
          skip_api_build: true
          api_location: "" # Api source code path - optional
  
  output-summary:
    name: "Output Summary"
    needs: [deploy-api, deploy-hub]
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Summary message
        run: |
          echo ">[!TIP] " >> $GITHUB_STEP_SUMMARY
          echo "> ### Deployment Complete!" >> $GITHUB_STEP_SUMMARY
          echo ">:globe_with_meridians: check EndatixAPI at ${{ needs.deploy-api.outputs.api-url }}" >> $GITHUB_STEP_SUMMARY
          echo ">:globe_with_meridians: check Endatix Hub at ${{ needs.deploy-hub.outputs.hub-url }}" >> $GITHUB_STEP_SUMMARY
