name: Deploy Endatix Hub to `endatix-hub-qad`

on:
  workflow_dispatch:
  push:
    branches:
      - release/qad
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - release/qad

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    defaults:
      run:
        working-directory: apps/endatix-hub

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false


      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          PRE_BUILD_COMMAND: npm install -g pnpm && pnpm install --frozen-lockfile
          CUSTOM_BUILD_COMMAND: pnpm build && cp -r .next/static .next/standalone/.next/ && cp -r public .next/standalone/
          ENDATIX_BASE_URL: ${{ secrets.ENDATIXHUB_API_BASE_URL }}
          SESSION_SECRET: ${{ secrets.ENDATIXHUB_NEXT_FORMS_COOKIE_DURATION_DAYS }}
          NEXT_FORMS_COOKIE_NAME: ${{ secrets.ENDATIXHUB_NEXT_FORMS_COOKIE_NAME }}
          NEXT_FORMS_COOKIE_DURATION_DAYS: ${{ secrets.ENDATIXHUB_SESSION_SECRET }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_PLANT_0DBFDE310 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/apps/endatix-hub" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_PLANT_0DBFDE310 }}
          action: "close"
